package gg.literal.bootstrap;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public final class EulaManager {

    private EulaManager() {
    }

    public static void verifyOrCreate(final Path eulaPath) throws BootstrapException {
        if (Files.notExists(eulaPath)) {
            createDefaultEula(eulaPath);
            throw new BootstrapException("EULA file was missing and has been generated. Set eula=true in eula.txt to continue.");
        }

        final List<String> lines;
        try {
            lines = Files.readAllLines(eulaPath, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw new BootstrapException("Unable to read eula.txt", ex);
        }

        for (String line : lines) {
            final String normalized = line.trim().toLowerCase();
            if (normalized.startsWith("eula=") && "eula=true".equals(normalized)) {
                return;
            }
        }

        throw new BootstrapException("EULA was not accepted. Set eula=true in eula.txt.");
    }

    private static void createDefaultEula(final Path eulaPath) throws BootstrapException {
        final String content = "# By changing the setting below to TRUE you are indicating your agreement to the Minecraft EULA (https://aka.ms/MinecraftEULA).\n"
            + "# This file was generated by Vector during startup.\n"
            + "eula=false\n";
        try {
            Files.writeString(eulaPath, content, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw new BootstrapException("Unable to create eula.txt", ex);
        }
    }
}
